### PR TITLE
Move to instance members

### PR DESCRIPTION
**Pull request by kingy444**
In response to https://github.com/fredrike/pydaikin/pull/16#issuecomment-2283131608 can we please move the definition to an instance member instead of a class member

### CODE REVIEW

**Comment by kingy444** [comment]
Have a failure in pylint due to https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/too-many-instance-attributes.html

@fredrike  how did you want to deal with that ?

**Comment by joostlek** [comment]
SSL context doesn't have to be in the constructor as that is not a mutable object like a dict or a list (iirc)

At this point just ignore pylint I guess. It would require a refactor to fix those and I'd rather get this in as quick as possible

**Comment by joostlek** [comment]
Thanks for picking this up btw, I was scared .2 would be another hellish release for a lot of people because of this

**Comment by kingy444** [comment]
@fredrike should be good to merge now

**Comment by fredrike** [comment]
Do we need this in HA ASAP too?

Can't one of you add yourself as contributors in HA and close the duplicate issues there..

**Comment by joostlek** [comment]
I am member, I can do that. I've been trying to do so over the last few days. Hell, I even remember the issue number 😂

**Comment by joostlek** [comment]
But yes, we want this, because this will probably fix the issues

**Comment by cremor** [comment]
> Do we need this in HA ASAP too?

Yes, see https://github.com/home-assistant/core/pull/123623 which is blocked to update to a version with this fix.

**Comment by fredrike** [comment]
I've pushed a new version to pypi.

**Pull request merged**
