### PR TITLE
Fix SSL Regression

### PR DESCRIPTION
**Pull request by kingy444**
Quick PR as alternate solution to https://github.com/fredrike/pydaikin/pull/14

This one should set the required defaults for all controller types

Apparently had some bad git log and this has pulled in some previous changes (that are already merged anyway)
im remote at the moment and working via RDP on my phone so hard to get this cleaned up atm 👀

### CODE REVIEW

**Comment by kingy444** [comment]
I think a mix of this PR and the tests from https://github.com/fredrike/pydaikin/pull/15 are a good fix

#15 would also fix but the cleanup this one provides cleans up some of the unneeded IF statements

**Review by jurgenweber — APPROVED** [review]

**Comment by jahmai** [comment]
RDP via phone. Kudos on the commitment 👍

**Comment by fredrike** [comment]
New version pushed to pypi: https://pypi.org/project/pydaikin/2.13.3/

**Comment by joostlek** [comment]
Hold up, let me add to this, creating a mutable object (like a dict in this case) at class level causes the dict to be shared over **all** instances of that class. This can lead to side effects and I don't think we want that here

**Comment by kingy444** [comment]
> Hold up, let me add to this, creating a mutable object (like a dict in this case) at class level causes the dict to be shared over **all** instances of that class. This can lead to side effects and I don't think we want that here

Isn't that what caused the issues in 2024.8.1 to start with ?

My understanding is
- 2024.8.0 broke due to SSL context being required on a particular model
- 2024.8.1 broke because headers did not exist on all child classes but all child classes shared the same get_response

This PR moved the `if headers is None` to the definition of the variable and then headers has a value set in the classes that need it

**Comment by cremor** [comment]
@kingy444 You are talking about classes in the inheritance hierarchy. But @joostlek is talking about multiple instances of the same class. So in this case multiple different Daikin AC units.
See also https://stackoverflow.com/questions/1680528/how-to-avoid-having-class-data-shared-among-instances

**Comment by joostlek** [comment]
Yes, I'm talking about multiple instances of this class, so it would work for users with 1 device, but people with 2 devices will see strange behaviour

**Pull request merged**
